# Site settings
title: billfeller.github.io
header-img: img/home-bg.jpg
description: "One Piece"
baseurl: "/jekyll"
url: "http://billfeller.github.io"

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
